linters:
  enable:
    - goconst
    - gocritic
    - gofmt
    - govet
    - prealloc
    - unconvert
    - unused
    - errcheck
    - ineffassign
    - containedctx
    - tenv
    - musttag
    - mirror
    - tagalign
    - zerologlint
    - copyloopvar
    - gosec
    - misspell
    - noctx
    - prealloc
    - protogetter
    - makezero

run:
  go: '1.22'
  timeout: 3m
