version: "3.6"
services:
  db:
    image: timescale/timescaledb:latest-pg15
    shm_size: 1g
    user: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5    
    logging: &bcd-logging
      options:
        max-size: 10m
        max-file: "5"
    command:
      - "postgres"
      - "-c"
      - "config_file=${POSTGRES_CONFIG:-/var/lib/postgresql/data/postgresql.conf}"

  api:
    restart: always
    image: ghcr.io/mavryk-network/bcdhub-api:${TAG:-master}
    build:
      context: .
      dockerfile: build/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 127.0.0.1:${BCD_API_PORT}:14000
    volumes:
      - ${SHARE_PATH}:/etc/bcd
    logging: *bcd-logging

  indexer:
    restart: always
    image: ghcr.io/mavryk-network/bcdhub-indexer:${TAG:-master}
    build:
      context: .
      dockerfile: build/indexer/Dockerfile
    env_file:
      - .env
    volumes:
      - ${SHARE_PATH}:/etc/bcd
    logging: *bcd-logging

volumes:
  db:
    driver: local
