name: Build GUI
on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build sandbox GUI
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: GUI image tags & labels
        id: meta-gui
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}-gui

      - name: GUI image build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/sandbox/Dockerfile
          build-args: |
            TAG=4.6.6
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-gui.outputs.tags }}
          labels: ${{ steps.meta-gui.outputs.labels }}
